### ISSUE TITLE
request: oshinko-deploy.sh should be smarter about its usage of `oc new-project`

### ISSUE THREAD

**Issue by elmiko** [radanalyticsio/oshinko-rest#104]
currently, a user expects that when the oshinko-deploy.sh is run it will create a new project and leave the user in that project's auth context. but, if the named project already exists and the user is not currently on that project then it is possible for them to be left in a different project. this can lead to some confusion with regards to any `oc` calls which may follow the script completion.

requested update

the deploy script should explicitly switch to the named project if it fails to create it.

**Comment by crobby** [comment]
Seems like a good idea.  +1
