### ISSUE TITLE
Support HEAD (or use a automagic declarative verb handler)

### ISSUE THREAD

**Issue by jayunit100** [radanalyticsio/oshinko-rest#2]
I think @elmiko is already working on/looking into this, just thought I'd brain dump in an issue. In  #1 i thought I found a bug in the response codes, but it was not a bug.  Actually, it was a feature request in disguise after I read some more.

Problem: It would be nice if oshinko supported head so that when testing it on openshift (which needs dns to resolve) you could do `curl -I` calls and so on.  Probably most REST APIs that support GET also support HEAD based on the fact that GET is a proper subset of HEAD.

(from http://www.ietf.org/rfc/rfc2616.txt)

```
9.4 HEAD

   The HEAD method is identical to GET except that the server MUST NOT
   return a message-body in the response. The metainformation contained
   in the HTTP headers in response to a HEAD request SHOULD be identical
   to the information sent in response to a GET request. This method can
   be used for obtaining metainformation about the entity implied by the
   request without transferring the entity-body itself. This method is
   often used for testing hypertext links for validity, accessibility,
   and recent modification.
```

Solution: 

Probably implementing a simple HEAD which returned the default headers would be a good start.  I don't know much about REST APIs so this may be non trivial if `GET` requires some complex processing. IIRC https://github.com/urfave/negroni is a good golang library which does declarative routing, and could be used as alternative to the current `[GET][/]` semantics used in the router.

**Comment by elmiko** [comment]
i'm closing this as it doesn't seem likely that we will need to implement HEAD support and migrating to a different http package (eg negroni) will require a rewrite of the server.

the payload for a GET request is small enough that the difference for requesting it instead of HEAD is negligible. additionally, the metainformation from the headers is minimal.
