### ISSUE TITLE
Consider making cluster name optional in the API and generating a name

### ISSUE THREAD

**Issue by tmckayus** [radanalyticsio/oshinko-rest#80]
Currently oshinko-s2i tooling does random cluster name generation for on-demand cluster creation, but this could just as easily be done in oshinko-rest if we make the cluster name optional instead of required on create.

Instead of a validation error, a missing name would cause a random name generation.  The generated name would be returned in the result, so the caller would have full knowledge of the name chosen.

Any name passed would still be respected.

**Comment by elmiko** [comment]
this is probably an improvement, plus we could then move some of the name scanning stuff in there as well. so, if a random name fails, it could try again before returning an error.

i'm ok with this. +1

**Comment by elmiko** [comment]
migrated to https://github.com/radanalyticsio/oshinko-cli/issues/93
