### ISSUE TITLE
The debug logging middleware can cause 502 errors in some circumstances

### ISSUE THREAD

**Issue by elmiko** [radanalyticsio/oshinko-rest#87]
It is possible for this middleware to not read all the data from the incoming buffer. The code should be improved to properly read the entire buffer length before close the connection.

This behavior can be seen by making a request for a new cluster from the webui against the rest server built from commit f227f3cb3131c0ed31f1bb01ea6e52f4e2b615a9

**Comment by crobby** [comment]
I can verify that I've seen this behavior.

**Comment by elmiko** [comment]
this is directly related to the middleware relying on reading the message content length from the header `Content-Length`. it appears that the webui does not generate this header which is why we only see it on POST/PUT/DELETE from the webui. i'm experimenting with a server side solution now.

**Comment by elmiko** [comment]
this has been fixed by PR #88
